ENV: win
# 手机号
Phone: 13979677669
# 短信验证码发送的线程数量
ThreadCount: 3
# 短信验证码发送的执行时机(默认60秒一次)
ExecutionCron: "*/60000 * * * * *"
# 会话的凭证(如果打印不是:[成功发送短信给医院,静等电话....],就根据Readme文件的指引去修改这个配置)
SSID : "imlp82983e089592958ffd20331faebd33ae"
# 电话轰炸前的的短信咨询内容
Content: "我的电话号码是xxx,微信也是xxx,我现在有很严重的肾脏疾病,因为一些不良好的饮食习惯和作息习惯,比较严重,已经影响到我的生活,想要求助一下医生,如果可以的话请电话联系我,谢谢"

